name: ${project.name}
main: com.michaelelin.NerdFlags.NerdFlagsPlugin
version: ${project.version}
description: ${project.description}
website: ${project.url}
database: false
depend: [WorldGuard, WorldEdit]
softdepend: [ProtocolLib, WGRegionEvents]
authors: [Dumbo52, Challenger2, Redwall_HP, bermudalocket]
api-version: 1.13